---
- name: ensure unzip is installed
  package:
    name: unzip
- name: download and extract Groovy
  unarchive:
    src: "{{ groovy_package_url }}"
    dest: "/opt"
    remote_src: yes
- name: create simbolic link from {{ groovy_install_dir }} to {{ groovy_home }}
  file:
    state: link
    dest: "{{ groovy_home }}"
    src: "{{ groovy_install_dir }}"
